CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name audio --using_model audio --using_contra False --using_cma False --using_weight_decay False --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both  --using_model both --using_contra False --using_cma False --using_weight_decay False --batch_size 16  --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name text  --using_model text --using_contra False --using_cma False --using_weight_decay False --batch_size 128 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_cma --using_model both --using_contra False --using_cma True --using_weight_decay False --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP/target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra --using_model both --using_contra True --using_cma False --using_weight_decay False --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra_cma --using_model both --using_contra True --using_cma True --using_weight_decay False --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP/target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra_decay --using_model both --using_contra True --using_cma False --using_weight_decay True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra_cma_decay --using_model both --using_contra True --using_cma True --using_weight_decay True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP/target_weight_0.1/

CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name audio --using_model audio --using_contra False --using_cma False --using_weight_decay False --using_graylabel True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both  --using_model both --using_contra False --using_cma False --using_weight_decay False --using_graylabel True --batch_size 16  --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name text  --using_model text --using_contra False --using_cma False --using_weight_decay False --using_graylabel True --batch_size 128 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_cma --using_model both --using_contra False --using_cma True --using_weight_decay False --using_graylabel True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP/target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra --using_model both --using_contra True --using_cma False --using_weight_decay False --using_graylabel True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra_cma --using_model both --using_contra True --using_cma True --using_weight_decay False --using_graylabel True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP/target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra_decay --using_model both --using_contra True --using_cma False --using_weight_decay True --using_graylabel True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP//target_weight_0.1_graylabel/
CUDA_VISIBLE_DEVICES=1,2 python trainer_hf.py  --exp_name both_contra_cma_decay --using_model both --using_contra True --using_cma True --using_weight_decay True --using_graylabel True --batch_size 16 --save_path /data/research_data/model_weights/EmoNet2/IEMOCAP/target_weight_0.1_graylabel/