path:
  train_csv: "./data/MELD/train.csv"
  dev_csv: "./data/MELD/dev.csv"
  test_csv: "./data/MELD/test.csv"
optimizer:
  batch_size: 32
  betas: [0.9, 0.999]
  eps: 0.000000001
  weight_decay: 0.0
  lr: 0.00005
step:
  max_epochs: 10
  warmup_ratio: 0.2
  num_cycle: 1
trainer:
  grad_clip_thresh: 1.5
  grad_acc: 1
model:
  n_head: 24
  dropout_p: 0.3
  using_contra: True
  using_cma: True
  using_graylabel: False
  contra_loss_weight: 0.3
  label_name: 'emotion'
  text_encoder: "roberta-base"
  audio_processor: "vitouphy/wav2vec2-xls-r-300m-phoneme"
  using_model: 'audio'