path:
  train_csv: "./data/IEMOCAP/train.csv"
  dev_csv: "./data/IEMOCAP/val.csv"
  test_csv: "./data/IEMOCAP/test.csv"
optimizer:
  batch_size: 32
  betas: [0.9, 0.999]
  eps: 0.000000001
  weight_decay: 0.0
  lr: 0.0001
step:
  max_epochs: 5
  warmup_ratio: 0.2
  num_cycle: 1
trainer:
  grad_clip_thresh: 1.5
  grad_acc: 1
exp_setting:
  using_contra: True
  using_cma: True
  using_graylabel: False
  dataset_name: 'IEMOCAP'
  num_class: 10
  using_model: 'audio'
model:
  n_head: 12
  dropout_p: 0.5
  contra_loss_weight: 0.3
  label_name: 'emotion'
  text_encoder: "roberta-base"
  audio_encoder: "vitouphy/wav2vec2-xls-r-300m-phoneme"